### ISSUE TITLE
Knex adapter does not work with PostgreSQL

### ISSUE THREAD

**Issue by smolijar** [smoliji/node-healthz#2]
Using healthz with knex on pg results in the following error.
```
show status - unrecognized configuration parameter "status"
```

Consider using more general [equivalent](https://stackoverflow.com/questions/3732422/select-from-nothing)

**Comment by smoliji** [comment]
In the planned future versions, built-in adapters won't be apart of the library, only custom checkers and user can then choose whatever they like.
