### ISSUE TITLE
Response time is missing in the new HTML UI

### ISSUE THREAD

**Issue by smoliji** [smoliji/node-healthz#4]
HTML view shipped in >=2.0.0 contains less info than the former JSON.

The time - total and for each checker, the error and the output. I'd like to include at least response time in some way, to indicate some issues with the particular check.

![image](https://github.com/smoliji/node-healthz/assets/6990251/18b6921f-1780-4405-a7ae-c1dbc54f67eb)
![image](https://github.com/smoliji/node-healthz/assets/6990251/1457f7bf-7c6d-4dd9-8b39-27b8b5166494)

**Comment by smoliji** [comment]
How about adding red/orange/green icon next to the checkmark?

https://icons.getbootstrap.com/?q=reception

**Comment by pavelsvagr** [comment]
Icon looks cool, but times should be still visible in my opinion. (hover effect?)

**Comment by smoliji** [comment]
> Icon looks cool, but times should be still visible in my opinion. (hover effect?)

Why not both?
![image](https://github.com/AckeeCZ/node-healthz/assets/6990251/23bd7590-600c-4e5e-8643-f7ac1ca74bee)

**Comment by smoliji** [comment]
Updated in https://github.com/AckeeCZ/node-healthz/pull/5
